name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v2
        if: github.event_name == 'push'
        with:
          ref: main
      - uses: xu-cheng/texlive-action/full@v1
        id: build
        with:
          run: |
            cp -r fonts /usr/share
            fc-cache -fv
            apk add make
            make
      - name: Update Latest Release
        if: github.event_name == 'push' && steps.build.outputs.exit_code == 0
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          commitish: ${{ github.sha }}
          name: Latest Release
          body: The Latest Release.
          files: cpp_simple_tutorial.pdf
          gzip: false
          allow_override: true
